pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - status-success=Travis CI - Pull Request
    # - "#approved-reviews-by>=1"  # TODO: uncomment when initial setup is done
      - "#changes-requested-reviews-by=0"
      - label=merge-when-green
    actions:
      merge:
        method: merge
        strict: smart

  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
