== Using a gRPC client in Play
:tabs-sync-option:

Pekko gRPC has special support to allow for seamless injection of generated clients in Play. To enable this, you
need first to enable the gRPC plugin as described in the https://pekko.apache.org/docs/pekko-grpc/current/client/walkthrough.html[client docs] and then add a source generator in `build.sbt`:

[tabs]
====
Scala::
+
[,scala]
----
import play.grpc.gen.scaladsl.PlayScalaClientCodeGenerator
pekkoGrpcExtraGenerators += PlayScalaClientCodeGenerator
libraryDependencies += "org.playframework" %% "play-grpc-runtime" % "{page-component-version}"
----
Java::
+
[,scala]
----
import play.grpc.gen.javadsl.PlayJavaClientCodeGenerator
pekkoGrpcExtraGenerators += PlayJavaClientCodeGenerator
libraryDependencies += "org.playframework" %% "play-grpc-runtime" % "{page-component-version}"
----
====
This will generate a Play module that provides all generated clients for injection. The module must be enabled
by adding it to the enabled modules in the `application.conf`.

You can then put the following `helloworld.proto` file in `app/protobuf`:

[,protobuf]
----
include::example$play-interop-test-scala/src/main/proto/helloworld.proto[tags=protoSources]
----

The module file is generated in `example.myapp.helloworld.grpc.helloworld.PekkoGrpcClientModule` by default for Scala
(or `example.myapp.helloworld.grpc.PekkoGrpcClientModule` by default for Java), which corresponds to the default value
of `flat_package` for Java/Scala. You can read more about this in https://pekko.apache.org/docs/pekko-grpc/current/proto.html[Services].

The exact package of the module will be based on the package the proto files are generated in, configured through
the `java_package` option in the proto-file (if there are multiple different gRPC generated clients the module will
be generated in the longest package prefix shared between the clients).

To hook it into Play, in `application.conf`:

[tabs]
====
Scala::
+
[,hocon]
----
include::example$play-interop-test-scala/src/main/resources/application.conf[tags=client-module-scala]
----
Java::
+
[,hocon]
----
include::example$play-interop-test-java/src/main/resources/application.conf[tags=client-module-java]
----
====

The clients are configured with entries under `pekko.grpc.client` named after the client (`gRPC` package name dot `ServiceName`),
again, in `application.conf`:

[,hocon]
----
include::example$play-interop-test-scala/src/main/resources/application.conf[tag=service-client-conf]
----

See https://pekko.apache.org/docs/pekko-grpc/current/client/configuration.html[Client Configuration] for more information on the available options. If the configuration
is not present for that client and it is used by some other component, the application start will fail with an exception
when injecting the client (see https://github.com/akka/akka-grpc/issues/271[#271]).

You can now use the client in a controller by injecting it:

[tabs]
====
Scala::
+
[,scala]
----
include::example$play-interop-test-scala/src/main/scala/controllers/MyController.scala[tags=using-client]
----
Java::
+
[,java]
----
include::example$play-interop-test-java/src/main/java/controllers/MyController.java[tags=using-client]
----
====
