= Serving gRPC from Play
:tabs-sync-option:

To be able to serve gRPC from a Play Framework app you must enable https://www.playframework.com/documentation/2.9.x/AkkaHttpServer#HTTP/2-support-(incubating)[HTTP/2 Support] with https://www.playframework.com/documentation/latest/ConfiguringHttps[HTTPS] and the ALPN agent.

WARNING: To use gRPC in Play Framework you must enable https://www.playframework.com/documentation/2.9.x/AkkaHttpServer#HTTP/2-support-(incubating)[HTTP/2 Support].

Generating classes from the gRPC service definition is done by adding the https://doc.akka.io/docs/akka-grpc/current/buildtools/sbt.html[Akka gRPC plugin to your sbt build] along with the Play gRPC generators:

[,scala,subs=attributes+]
----
// in project/plugins.sbt:
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc" % "{akka-grpc-version}")
resolvers += Resolver.sonatypeCentralSnapshots
libraryDependencies += "com.typesafe.play" %% "play-grpc-generators" % "{page-component-version}"
----

Then you need to enable the Play server side code generator in `build.sbt`:

[tabs,sync-group-id=lang]
====
Scala::
+
[,scala,subs=attributes+]
----
enablePlugins(AkkaGrpcPlugin)
import play.grpc.gen.scaladsl.PlayScalaServerCodeGenerator
akkaGrpcExtraGenerators += PlayScalaServerCodeGenerator
libraryDependencies += "com.typesafe.play" %% "play-grpc-runtime" % "{page-component-version}"
----
Java::
+
[,scala,subs=attributes+]
----
enablePlugins(AkkaGrpcPlugin)
import play.grpc.gen.javadsl.PlayJavaServerCodeGenerator
akkaGrpcExtraGenerators += PlayJavaServerCodeGenerator
libraryDependencies += "com.typesafe.play" %% "play-grpc-runtime" % "{page-component-version}"
----
====

The plugin will look for `.proto` service descriptors in `app/protobuf` and output an abstract class per service that you then implement, so for example for the following protobuf descriptor:

[,protobuf]
----
include::example$play-interop-test-scala/src/main/proto/helloworld.proto[tags=protoSources]
----

You will get an abstract class named [.lang-scala]#`example.myapp.helloworld.grpc.helloworld.AbstractGreeterServiceRouter`.# [.lang-java]#`example.myapp.helloworld.grpc.AbstractGreeterServiceRouter`.#
Create a concrete subclass implementing this wherever you see fit in your project, let's say `controller.GreeterServiceImpl` like so:

[tabs,sync-group-id=lang]
====
Scala::
+
[,scala]
----
include::example$play-interop-test-scala/src/main/scala/controllers/GreeterServiceImpl.scala[tags=service-impl]
----
Java::
+
[,java]
----
include::example$play-interop-test-java/src/main/java/controllers/GreeterServiceImpl.java[tags=service-impl]
----
====


And then add the router to your Play `conf/routes` file. Note that the router already knows its own path since it is based on the package name and service name of the service and therefore the path `/` is enough to get it to end up in the right place (in this example the path will be `/helloworld.GreeterService`). It cannot be added at an arbitrary path (if you try to do so an exception will be thrown when the router is started).

```
->     /   controllers.GreeterServiceImpl
```

A gRPC client can now connect to the server and call the provided services.
