addSbtPlugin("com.eed3si9n"            % "sbt-buildinfo"    % "0.11.0")
addSbtPlugin("com.lightbend.akka"      % "sbt-paradox-akka" % "0.43")
addSbtPlugin("com.typesafe.sbt"        % "sbt-twirl"        % "1.5.1")
addSbtPlugin("de.heikoseeberger"       % "sbt-header"       % "5.7.0")
addSbtPlugin("org.scalameta"           % "sbt-scalafmt"     % "2.4.6")
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc"    % "1.1.1")
addSbtPlugin("com.github.sbt"          % "sbt-ci-release"   % "1.5.10")
